---
##################################
# Check requirements before insall
##################################
- name: Set Required Package
  set_fact: packages="['bash','git','curl','unzip']"

- name: Ensure dependancies presence's
  package:
    name: "{{ packages }}"
    state: present
