---
##################################
# Configure ZSH Plugins
##################################
- name: "Execute extra plugin command"
  shell: |
    set -o pipefail
    source ~/.zshrc ; {{ item }}
  args:
    executable: /bin/zsh
  with_items:
    - "{{ oh_my_zsh_custom_plugins_command }}"
  when: oh_my_zsh_custom_plugins_command is defined
