---
##################################
# Install ZSH and oh-my-zsh
##################################
- name: Install zsh
  package: name=zsh state=present
  register: installation
  become: true

- name: Look for oh-my-zsh
  stat:
    path: "~/.oh-my-zsh"
  register: ohmyzsh

- name: Gather package facts
  package_facts:
    manager: auto

- block:
   - name: Download oh-my-zsh Installer
     get_url:
       url: "{{ oh_my_zsh_url }}"
       dest: /tmp/zsh-installer.sh

   - name: Install oh-my-zsh
     script: /tmp/zsh-installer.sh
  when: not ohmyzsh.stat.exists and '"zsh" in ansible_facts.packages'

- name: "Change shell for {{ ansible_user }} to /bin/zsh"
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true
